### ISSUE TITLE
Use get-random-bytes-polypony polyfill

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/sodium-javascript#1]
Does the system work if - instead of replacing the whole code in `./randombytes.js` - the [setup in tests](https://github.com/consento-org/sodium-javascript/blob/6322cb10a201caa26ab70bc53a567d4db6d074e1/test.js#L1) simply uses the polyfill: `require('get-random-values-polypony').polyfill()`?

**Comment by RangerMauve** [comment]
Tried using the polyfill method. Getting weird error messages from Browserstack. Not obvious what's up yet. Will investigate more tomorrow.

https://github.com/consento-org/sodium-javascript/runs/1229933105

https://app-automate.browserstack.com/dashboard/v2/builds/df17bcae2015a6bd6126f8fa943e3152e236dc5e/sessions/359dc0be8b406f93241225fe1c692dffea3f4a99

**Comment by RangerMauve** [comment]
Polyfill works! Need to load it before sodium-javascript loads in react-native
