### ISSUE TITLE
Fix sign_keypair upstream

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/sodium-javascript#3]
sign_keypair has been fixed in https://github.com/consento-org/sodium-javascript/commit/6d9193e2def9079f2f7e7980cbfe39f87cbb9a8a#diff-c93988f13570154575763144cbf8d003 - let's send that patch upstream!

**Comment by RangerMauve** [comment]
Problem was sodium-test was out of date, latest one doesn't need this change
