### ISSUE TITLE
Fix window.close in tests upstream

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/sodium-javascript#5]
To make the tests run `window.close` is tested more thoroughly before execution.
https://github.com/consento-org/sodium-javascript/commit/6d9193e2def9079f2f7e7980cbfe39f87cbb9a8a#diff-1dd241c4cd3fd1dd89c570cee98b79ddR7

Should this be fixed upstream?

**Comment by RangerMauve** [comment]
Fixed upstream: https://github.com/sodium-friends/sodium-javascript/pull/49
